[versions]
assertj = "3.27.7"
dokka = "2.1.0"
java = "17"
jreleaser = "1.22.0"
junit = "5.14.2"
kotest = "6.1.3"
kotlin = "2.3.10"
kotlinxCoroutines = "1.10.2"
ktlint = "1.8.0"
ktlintPlugin = "14.0.1"
logbackAccess = "2.0.7"
logbackClassic = "1.5.22"
mockk = "1.14.9"
reactorNetty = "1.2.13"
slf4j = "2.0.17"
springBoot = "3.5.9"

[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
dokka-plugin = { group = "org.jetbrains.dokka", name = "org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
dokka-javadoc-plugin = { group = "org.jetbrains.dokka-javadoc", name = "org.jetbrains.dokka-javadoc.gradle.plugin", version.ref = "dokka" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotest-assertions-core-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
kotlin-plugin = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }
ktlint-plugin = { group = "org.jlleitschuh.gradle.ktlint", name = "org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlintPlugin" }
logback-access-common = { group = "ch.qos.logback.access", name = "logback-access-common", version.ref = "logbackAccess" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackClassic" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
reactorNetty-http = { group = "io.projectreactor.netty", name = "reactor-netty-http", version.ref = "reactorNetty" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
spring-boot-autoconfigureProcessor = { group = "org.springframework.boot", name = "spring-boot-autoconfigure-processor", version.ref = "springBoot" }
spring-boot-configurationProcessor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "springBoot" }
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-reactorNetty = { group = "org.springframework.boot", name = "spring-boot-starter-reactor-netty", version.ref = "springBoot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux", version.ref = "springBoot" }

[plugins]
dokka = { id = "org.jetbrains.dokka" }
conventions = { id = "conventions" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
kotlin-springPlugin = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }